[package]
name = "ingest"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.89"
axum = "0.8"
chrono = "0.4"
quick-xml = "0.37"
regex = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[[bin]]
name = "ingest"
path = "src/main.rs"

[[bin]]
name = "dummy"
path = "src/dummy.rs"

[[bin]]
name = "bench_parser"
path = "src/bench_parser.rs"

[[bin]]
name = "explore"
path = "src/explore.rs"
